// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Empty: typeof import('./src/components/Global/Empty/index.vue')['default']
    FormWrap: typeof import('./src/components/Global/FormWrap/index.vue')['default']
    NoPromission: typeof import('./src/components/NoPromission.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondWrap: typeof import('./src/components/Global/SecondWrap/index.vue')['default']
    SendCode: typeof import('./src/components/SendCode/index.vue')['default']
    Skeleton: typeof import('./src/components/Global/Skeleton/index.vue')['default']
    SvgIcon: typeof import('./src/components/Global/SvgIcon/index.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanLoading: typeof import('vant/es')['Loading']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanSkeleton: typeof import('vant/es')['Skeleton']
    WxOpenLaunchWeappWrap: typeof import('./src/components/WxOpenLaunchWeappWrap.vue')['default']
  }
}

export {}
